# The first stage caches dependencies
FROM maven:3.9.10-amazoncorretto-21 AS dependencies

WORKDIR /app
COPY pom.xml .
COPY bom/pom.xml bom/pom.xml
COPY consumer/pom.xml consumer/pom.xml
COPY models/pom.xml models/pom.xml
COPY producer/pom.xml producer/pom.xml

RUN mvn -pl "models,producer" -B -e org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline -DexcludeArtifacts=models

# The second stage builds the image
FROM maven:3.9.10-amazoncorretto-21 AS builder

WORKDIR /app
COPY --from=dependencies /root/.m2 /root/.m2
COPY --from=dependencies /app /app
COPY models/src /app/models/src
COPY producer/src /app/producer/src

RUN mvn -pl "models,producer" -B -e clean install -DskipTests

# The third stage prepares the runtime environment
FROM openjdk:21-slim

WORKDIR /app
COPY --from=builder /app/producer/target/*.jar /app.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]
