services:
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: agility
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
      INFLUXD_REPORTING_DISABLED: true
    #    volumes:
    #      - type: volume
    #        source: influxdb2-data
    #        target: /var/lib/influxdb2
    #      - type: volume
    #        source: influxdb2-config
    #        target: /etc/influxdb2
    #volumes:
    #  influxdb2-data:
    #  influxdb2-config:
